binaryGap
AcademyJunior/alghoritms pull request #4
Opened 2017-04-09 08:45 UTC by lukozog

2017-04-12 20:44 UTC, jankowskip requested changes

2017-04-12 20:44 UTC, jankowskip commented on src/BinaryGapOrzech.java
> +/**
Wylacz generowanie komentarzy w InteliJ, przy okazji gdzie sa importy, przeciez ten kod sie nie kompiluje

2017-04-12 20:44 UTC, jankowskip commented on src/BinaryGapOrzech.java
> +        String nat=Integer.toBinaryString(N);
nat jako nazwa zmiennej nic nie mowi

2017-04-12 20:44 UTC, jankowskip commented on src/BinaryGapOrzech.java
> +        List<String> myList = new ArrayList<String>(Arrays.asList(nat.split("")));
myList to bardzo slaba nazwa dla zmiennej, przy okazji masz stringa a zamieniasz go na tablice a pozniej na liste, nie wiem po co, skorzystaj ze stringa, mozesz po nim przeleciec jak po liscie, uzyj metod lenth i charAt

2017-04-12 20:44 UTC, jankowskip commented on src/BinaryGapOrzech.java
> +        for(int i=0;i<myList.size() && myList.size()!=0;i++){
Co to jest:D  `myList.size()!=0` przeciez jak lista bedzie miala rozmiar zero to 0<myList.size zwroci false i nie wejdzie do petli wywal to

2017-04-12 20:44 UTC, jankowskip commented on src/BinaryGapOrzech.java
> +                    binaryGap=0;
Po co ten dodatkowy warunek skoro tu i tu ustawiasz binaryGap na zero
```
      binaryGap=0;
  }
  else
      binaryGap=0;
```
usun tego elsa i ustaw binaryGap na zero pod ifem

2017-04-12 20:46 UTC, jankowskip commented on src/BinaryGapOrzech.java
> +                    binaryGap=0;
Rob na zadania osobne branche, bedzie mi wygodniej wam obu sprawdzac, nazwales branch binary gap, pull review binary gap a dodales tez OddOccurrencesInArray, tego drugiego zrobie ci review pozniej wiec poki co nie merguj brancha.

2017-04-13 17:07 UTC, lukozog commented
ok, zmiany poczynione w oparciu o wskazówki

2017-04-15 20:02 UTC, merged